[project]
name = "exo-hand-measurement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "matplotlib>=3.9.2",
    "opencv-python>=4.10.0.84",
    "pillow>=11.0.0",
]
